{% set name = "gradientai" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gradientai-{{ version }}.tar.gz
  sha256: 4198ba19fb46f0c64e5ce702d13a36e79be32348781bfe9fb6cd37833065ac1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0.0
    - aenum >=3.1.11
    - pydantic >=1.10.15,<3
    - python-dateutil >=2.8.2
    - urllib3 >=1.25.3

test:
  imports:
    - gradientai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Preemo-Inc/gradientai-python-sdk
  summary: Gradient AI API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
